
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package net.ddns.lai.boardpayment;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-08-27T21:17:22.625+02:00
 * Generated source version: 3.1.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "BoardPayment",
                      portName = "BoardPayment",
                      targetNamespace = "http://www.lai.ddns.net/BoardPayment/",
                      wsdlLocation = "file:/home/giovanni/workspace/LAIBoardgame/BoardPaymentWS/WebContent/WEB-INF/wsdl/BoardPayment.wsdl",
                      endpointInterface = "net.ddns.lai.boardpayment.BoardPayment")
                      
public class BoardPaymentImpl implements BoardPayment {

    private static final Logger LOG = Logger.getLogger(BoardPaymentImpl.class.getName());

    /* (non-Javadoc)
     * @see net.ddns.lai.boardpayment.BoardPayment#requestPayment(net.ddns.lai.schema.boardpayment.RequestPaymentType  payment )*
     */
    public net.ddns.lai.schema.boardpayment.SuccessOrFailure requestPayment(net.ddns.lai.schema.boardpayment.RequestPaymentType payment) { 
        LOG.info("Executing operation requestPayment");
        System.out.println(payment);
        try {
            net.ddns.lai.schema.boardpayment.SuccessOrFailure _return = net.ddns.lai.schema.boardpayment.SuccessOrFailure.FAILURE;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
