package net.ddns.lai.boardpayment;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-08-27T21:17:22.662+02:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "BoardPayment", 
                  wsdlLocation = "file:/home/giovanni/workspace/LAIBoardgame/BoardPaymentWS/WebContent/WEB-INF/wsdl/BoardPayment.wsdl",
                  targetNamespace = "http://www.lai.ddns.net/BoardPayment/") 
public class BoardPayment_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.lai.ddns.net/BoardPayment/", "BoardPayment");
    public final static QName BoardPayment = new QName("http://www.lai.ddns.net/BoardPayment/", "BoardPayment");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/giovanni/workspace/LAIBoardgame/BoardPaymentWS/WebContent/WEB-INF/wsdl/BoardPayment.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BoardPayment_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/giovanni/workspace/LAIBoardgame/BoardPaymentWS/WebContent/WEB-INF/wsdl/BoardPayment.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BoardPayment_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BoardPayment_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BoardPayment_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public BoardPayment_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BoardPayment_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BoardPayment_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns BoardPayment
     */
    @WebEndpoint(name = "BoardPayment")
    public BoardPayment getBoardPayment() {
        return super.getPort(BoardPayment, BoardPayment.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BoardPayment
     */
    @WebEndpoint(name = "BoardPayment")
    public BoardPayment getBoardPayment(WebServiceFeature... features) {
        return super.getPort(BoardPayment, BoardPayment.class, features);
    }

}
