package net.ddns.lai.boardpayment;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-08-27T21:17:22.655+02:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://www.lai.ddns.net/BoardPayment/", name = "BoardPayment")
@XmlSeeAlso({net.ddns.lai.schema.boardpayment.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BoardPayment {

    @WebMethod(operationName = "RequestPayment", action = "RequestPayment")
    @WebResult(name = "paymentResult", targetNamespace = "http://www.lai.ddns.net/BoardPayment/", partName = "paymentResult")
    public net.ddns.lai.schema.boardpayment.SuccessOrFailure requestPayment(
        @WebParam(partName = "payment", name = "payment", targetNamespace = "http://www.lai.ddns.net/BoardPayment/")
        net.ddns.lai.schema.boardpayment.RequestPaymentType payment
    );
}
