package net.ddns.lai.boardbooking;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-08-29T01:17:46.746+02:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "BoardBooking", 
                  wsdlLocation = "file:/home/giovanni/workspace/LAIBoardgame/BoardBookingWS/WebContent/WEB-INF/wsdl/BoardBooking.wsdl",
                  targetNamespace = "http://www.lai.ddns.net/BoardBooking/") 
public class BoardBooking_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.lai.ddns.net/BoardBooking/", "BoardBooking");
    public final static QName BoardBooking = new QName("http://www.lai.ddns.net/BoardBooking/", "BoardBooking");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/giovanni/workspace/LAIBoardgame/BoardBookingWS/WebContent/WEB-INF/wsdl/BoardBooking.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BoardBooking_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/giovanni/workspace/LAIBoardgame/BoardBookingWS/WebContent/WEB-INF/wsdl/BoardBooking.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BoardBooking_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BoardBooking_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BoardBooking_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public BoardBooking_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BoardBooking_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BoardBooking_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns BoardBooking
     */
    @WebEndpoint(name = "BoardBooking")
    public BoardBooking getBoardBooking() {
        return super.getPort(BoardBooking, BoardBooking.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BoardBooking
     */
    @WebEndpoint(name = "BoardBooking")
    public BoardBooking getBoardBooking(WebServiceFeature... features) {
        return super.getPort(BoardBooking, BoardBooking.class, features);
    }

}
