
package net.ddns.lai.boardbooking;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-08-29T01:17:46.454+02:00
 * Generated source version: 3.1.6
 * 
 */
public final class BoardBooking_BoardBooking_Client {

    private static final QName SERVICE_NAME = new QName("http://www.lai.ddns.net/BoardBooking/", "BoardBooking");

    private BoardBooking_BoardBooking_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BoardBooking_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BoardBooking_Service ss = new BoardBooking_Service(wsdlURL, SERVICE_NAME);
        BoardBooking port = ss.getBoardBooking();  
        
        {
        System.out.println("Invoking abortBoardgameBooking...");
        java.lang.String _abortBoardgameBooking_bookingAbort = "_abortBoardgameBooking_bookingAbort501311009";
        net.ddns.lai.schema.boardbooking.SuccessOrFailure _abortBoardgameBooking__return = port.abortBoardgameBooking(_abortBoardgameBooking_bookingAbort);
        System.out.println("abortBoardgameBooking.result=" + _abortBoardgameBooking__return);


        }
        {
        System.out.println("Invoking bookingDetails...");
        java.lang.String _bookingDetails_requestDetails = "_bookingDetails_requestDetails1639742066";
        net.ddns.lai.schema.boardbooking.BookingDetailsListType _bookingDetails__return = port.bookingDetails(_bookingDetails_requestDetails);
        System.out.println("bookingDetails.result=" + _bookingDetails__return);


        }
        {
        System.out.println("Invoking requestPaymentData...");
        net.ddns.lai.schema.boardbooking.EmptyType _requestPaymentData_payment = new net.ddns.lai.schema.boardbooking.EmptyType();
        net.ddns.lai.schema.boardbooking.RequestPaymentDataAnswerType _requestPaymentData__return = port.requestPaymentData(_requestPaymentData_payment);
        System.out.println("requestPaymentData.result=" + _requestPaymentData__return);


        }
        {
        System.out.println("Invoking openSession...");
        net.ddns.lai.schema.boardbooking.OpenSessionType _openSession_openSession = new net.ddns.lai.schema.boardbooking.OpenSessionType();
        _openSession_openSession.setUser("User-916512149");
        net.ddns.lai.schema.boardbooking.SuccessOrFailure _openSession__return = port.openSession(_openSession_openSession);
        System.out.println("openSession.result=" + _openSession__return);


        }
        {
        System.out.println("Invoking listGames...");
        net.ddns.lai.schema.boardbooking.EmptyType _listGames_listGames = new net.ddns.lai.schema.boardbooking.EmptyType();
        net.ddns.lai.schema.boardbooking.GameListType _listGames__return = port.listGames(_listGames_listGames);
        System.out.println("listGames.result=" + _listGames__return);


        }
        {
        System.out.println("Invoking bookingGroups...");
        net.ddns.lai.schema.boardbooking.EmptyType _bookingGroups_requestBookingGroups = new net.ddns.lai.schema.boardbooking.EmptyType();
        net.ddns.lai.schema.boardbooking.BookingGroupListType _bookingGroups__return = port.bookingGroups(_bookingGroups_requestBookingGroups);
        System.out.println("bookingGroups.result=" + _bookingGroups__return);


        }
        {
        System.out.println("Invoking bookBoardgame...");
        net.ddns.lai.schema.boardbooking.BookingDataType _bookBoardgame_bookingData = new net.ddns.lai.schema.boardbooking.BookingDataType();
        java.time.LocalDate _bookBoardgame_bookingDataBaseDate = null;
        _bookBoardgame_bookingData.setBaseDate(_bookBoardgame_bookingDataBaseDate);
        java.time.LocalDate _bookBoardgame_bookingDataEndDate = null;
        _bookBoardgame_bookingData.setEndDate(_bookBoardgame_bookingDataEndDate);
        _bookBoardgame_bookingData.setGame("Game-1733646840");
        net.ddns.lai.schema.boardbooking.BoardgameBookingAnswerType _bookBoardgame__return = port.bookBoardgame(_bookBoardgame_bookingData);
        System.out.println("bookBoardgame.result=" + _bookBoardgame__return);


        }

        System.exit(0);
    }

}
